[project]
name = "langchain-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "langchain>=0.0.27",
    "openai>=0.8.0",
]
